### ISSUE TITLE
Swagger-UI도입

### ISSUE THREAD

**Issue by Anzanda** [skkuding/next#107]
### Describe the problem and solution

Fe/Be를 구분하여 개발하는 프로세스에 API문서화는 필수입니다. Nest.js에서 공식지원하기도 하고 가장 유명한 Swagger-UI를 도입하고자 합니다. 

``` bash
$ pnpm install --save @nestjs/swagger swagger-ui-express
```

뿐 아니라 nest.js의 `main.ts`에도 설정할 부분이 있습니다.

``` typescript
// By Nest.js document
 const config = new DocumentBuilder()
    .setTitle('Cats example')
    .setDescription('The cats API description')
    .setVersion('1.0')
    .addTag('cats')
    .build();
 const document = SwaggerModule.createDocument(app, config);
 SwaggerModule.setup('api', app, document);
```
공통적인 부분이 있으므로 하나의 Feature로 올려서 해결하고자 합니다.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by Anzanda** [comment]
Swagger-UI말고도 다른 대안도 고려해볼까 합니다. 따라서 태그를 바꾸도록 하겠습니다... 일단 급한 불부터 끄고 API문서화를 보도록하죠.

**Comment by cranemont** [comment]
Testing tool로써의 역할이 다른 대안들로는 대체가 불가능하기도 하고, 다른 대안들은 hosting을 신경써야 하거나 매번 문서 업데이트를 해줘야 하는 단점이 커서 swagger 사용하도록 하겠습니다..!
