### ISSUE TITLE
Entity builder pattern 적용

### ISSUE THREAD

**Issue by mixxeo** [skkuding/next#111]
## 개념 설명
**Entity**는 실제 데이터베이스 테이블에 존재하는 칼럼들을 필드로 가지는 클래스입니다. 따라서, 각 데이터베이스 테이블과 1:1로 매핑되며 해당 테이블이 가지지 않는 칼럼을 필드로 가져서는 안됩니다.
많은 비즈니스 로직들이 Entity 클래스를 기준으로 동작하기 때문에 Entity 클래스는 일관성과 안전성을 보장해야합니다. 따라서 Entity는 setter대신 Builder를 사용합니다.
(Builder를 이용해서 초기화 하는 경우 불변 객체로 활용할 수 있고, 불변 객체로 만들면 전달 과정에서 데이터가 변조되지 않음을 보장합니다.)

## 필요성
Entity Builder 패턴을 도입하여  `POST`, `PUT` 요청 시 request body로 받은 데이터가 비즈니스 로직을 수행한 뒤 실제 데이터베이스에 저장되기 전 Validation 단계를 거치도록 합니다.

## 적용 방안
1. 각 Module은 관련 DB 테이블에 매핑되는 Entity class를 포함합니다.
- 각 Entity class는 매핑되는 prisma model type을 implement합니다.
- Entity class는 `Builder` method를 가집니다.
- Entity class의 각 attribute에는 class-validator를 적용합니다.
2. Service 구현시 필요한 DTO class는 Entity class를 `PickType` 하여 생성합니다.
3. `POST`, `PUT` 요청을 처리하는 service에서 데이터베이스에 데이터를 저장하기 전 `Bulider`로 Entity 객체를 생성하고 생성한 객체를 활용해 데이터베이스에 데이터를 저장합니다.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by aintbe** [comment]
prisma schema를 이용하여 데이터 타입을 정의하고 있는 현 구조에서는 이중으로 Entity 클래스를 사용하는 것이 크게 유의미하지 않을 듯하고, 어떤 PR에도 활용되고 있지 않으므로 이슈 닫습니다! 추후 해당 패턴이 필요해지면 MicroORM을 도입하겠습니다.😸
