### ISSUE TITLE
[Feature] Common(Molecule)-Modal  

### ISSUE THREAD

**Issue by djc06048** [skkuding/next#124]
### 🎨 Component Image

<div style="flex-direction: row">

<img width="152" alt="image" src="https://user-images.githubusercontent.com/62535887/178968287-ecd8190b-7b84-49e9-aa7c-3901ee021a1f.png">

<img width="148" alt="image" src="https://user-images.githubusercontent.com/62535887/178968332-74f0996b-2535-4fd5-bfa5-5082d8f00f8c.png">

<img width="147" alt="image" src="https://user-images.githubusercontent.com/62535887/178968381-06affd04-eb71-49e5-8446-5ac61ad55eb7.png">
</div>

### ✏️ Describe component

User의 회원가입, 로그인, 비밀번호 찾기 모달입니다.

### ☁️ Props

- Modal의 title 
- Modal 스타일(제목 색, modal 사이즈)

### 🔎 Using Page

* Home page
등 모달이 이용되는 페이지

### 🏷 Required Component

#68 Button
#95 InputItem

**Comment by SOLBI1028** [comment]
모달은 home 뿐만아니라 다른 페이지에서도 많이 사용되기 때문에, 하나의 종류에 국한된 모달이 아니라 모든 페이지에서 공통적으로 적용되는 둥근 흰색 배경 + 닫기버튼을 구현해주시면 될 것같아요!
그리고 추후에 각 page를 구현하면서 구체적인 모달을 구현하면 좋을 것 같습니다:)
