### ISSUE TITLE
Popover 구현 : Vue3 Popper library 도입

### ISSUE THREAD

**Issue by SOLBI1028** [skkuding/next#135]
## Problem
#125 를 구현하던 중 다음과 같은 문제가 생겼습니다.

1. `Popover.vue` 하나의 파일에 hover를 하는 대상과 말풍선(hover 했을 때 보이는 text)을 구현할 경우
```
// Popover.vue
  <transition>
  ~~
  </transition>
  <slot>
```
popover 컴포넌트를 하나만 사용한다면 사진과 같이 문제 없이 동작하지만, 여러개의 popover 컴포넌트를 flex를 이용하여 가로 정렬할 경우 다음 이미지와 같이 하나의 컴포넌트가 차지하는 width값이 줄어들어 말풍선의 크기에 영향을 줍니다. 그래서 말풍선의 width가 hover 대상의 width보다 큰 경우에 문제가 생깁니다.
<img width="320" alt="image" src="https://user-images.githubusercontent.com/75013515/179727023-31478bc2-1497-47f6-b9e2-c3ad9595f175.png">
<img width="235" alt="image" src="https://user-images.githubusercontent.com/75013515/179728184-4407a657-5438-4238-b488-fdb5ce13ef10.png">

2. `Popover.vue` 파일에 말풍선을 구현하고, Popover를 사용하는 페이지에서 hover 대상을 지정하는 경우
```
//Popover.vue
<transition>
~~
</transition>

// index.vue
<Popover
  target="target"
/>
<Button ref="target">Button</Button>
```
여러개 사용하여도 hover 대상의 width값에 영향을 주지 않는다는 장점이 있었지만, hover 대상의 위치를 파악하기가 어렵다는 문제가 있었습니다.

## Solution
[Vue3 Popper library](https://valgeirb.github.io/vue3-popper/guide/what-is-vue-3-popper.html) 사용
- popperJS를 사용한 라이브러리로, 사용 방법이 굉장히 쉽고 저희 플랫폼에서 필요한 커스텀을 모두 지원합니다.
<img width="209" alt="image" src="https://user-images.githubusercontent.com/75013515/179733508-fc96654a-7ac3-40a5-9ed9-0708b6fdade4.png">

## Discussion
Vue3 Popper 라이브러리를 사용하는게 좋을지, 혹은 제가 시도한 두가지 방법이 아니라 해당 컴포넌트를 구현할 수 있는 더 좋은 방법이 있는지 의견 주시면 참고해서 구현하도록 하겠습니다.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by dotoleeoak** [comment]
Popper가 어디 쓰이나요? hover 했을 때 쓰이는 지 click 했을 때 쓰이는 지도 궁금해요!

**Comment by dotoleeoak** [comment]
만약 직접 구현한다면 Teleport로 구현가능할 것 같아요.
Vue에서 modal이나 alert 같은 것들이 Teleport로 많이 구현돼요.
https://vuejs.org/guide/built-ins/teleport.html

**Comment by SOLBI1028** [comment]
<img width="683" alt="image" src="https://user-images.githubusercontent.com/75013515/179744014-9ec6e99d-efe4-45b7-9ec3-4b6184c4fef1.png">
<img width="289" alt="image" src="https://user-images.githubusercontent.com/75013515/179744321-1c8837e3-1bea-4991-8a8c-7fc7d9bc2cbb.png">

group admin page 에 있는 테이블/모달인데, 이렇게 option이나 리스트에 아이콘 버튼이 여러개 있어서 어떤 버튼인지 설명이 필요할때 해당 버튼에 hover 하면 설명을 짧게 명시하는데에 사용하려고 합니다!
오 Teleport도 알아보고 구현해보도록 하겠습니다!

**Comment by goo314** [comment]
그냥 단순하게 말풍선의 스타일을 `absolute`로 주면 안되나요~?
```vue
<!-- Popover.vue -->
<button class="relative">
    <div class="absolute bottom-full"> <!--말풍선-->
    </div>
</button>
```
아래는 위 코드로 간단하게 짜서 Popover 2개를 나란히 나열한 모습입니다
<img width="770" alt="image" src="https://user-images.githubusercontent.com/62930375/180016100-4a408081-bd13-46fb-85d8-fa685b68b66b.png">
