### ISSUE TITLE
Setup base file for super admin/manager and group admin

### ISSUE THREAD

**Issue by SOLBI1028** [skkuding/next#145]
### Describe the problem and solution

Super admin / manager과 group admin을 위한 base file을 설정합니다.
```
/common

/admin // admin file
  /pages
    /notice
    /contest
  ...

/manager // group manager file
  /pages
    /notice.vue
    /contest.vue
    ...
  /[groupId] //group manager - group detail file
    /notice
   ...

/user  //user file
  /notice
  /contest
  ...
```

### Discussion
`/manager/pages/[groupId]/notice` 디렉토리에서 notice edit, create 파일 관련해서 고민이 있습니다.
create 페이지는 notice id값이 없어서 `notice/create.vue`로, 
edit 페이지는 특정 Notice에 대한 수정이기 때문에 `notice/[noticeId]/edit.vue`의 형태가 되어야 할 것 같은데,
create파일과 edit 파일은 내용유무만 다르고 형식이 똑같습니다.
이럴땐 동일한 형식에 대해 component를 생성하고 create.vue / edit.vue에서 컴포넌트를 재사용할지,
혹은 라우팅을 다르게 하는 방법이 있을지 의견 남겨주시면 감사하겠습니다!

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by dotoleeoak** [comment]
admin 부분은 제가 작업할까 하는데, `frontend-admin`으로 따로 package 만드는 거 어떤가요?

**Comment by dotoleeoak** [comment]
> 동일한 형식에 대해 component를 생성하고 create.vue / edit.vue에서 컴포넌트를 재사용할지,
혹은 라우팅을 다르게 하는 방법이 있을지 의견 남겨주시면 감사하겠습니다!

이건 컴포넌트 공유하는 게 좋아보입니다~!

**Comment by SOLBI1028** [comment]
> admin 부분은 제가 작업할까 하는데, `frontend-admin`으로 따로 package 만드는 거 어떤가요?

package를 따로 만든다는게 지금 frontend / backend 처럼 frontend-admin를 분리하자는 말씀이실까요?!

**Comment by dotoleeoak** [comment]
> package를 따로 만든다는게 지금 frontend / backend 처럼 frontend-admin를 분리하자는 말씀이실까요?!

네넹

**Comment by dotoleeoak** [comment]
일반 유저 페이지는 나중에 SSR 적용할 예정인데, 보통 admin 페이지는 SPA가 적절해서 아예 패키지를 구분해서 렌더링하려고요

**Comment by SOLBI1028** [comment]
> 일반 유저 페이지는 나중에 SSR 적용할 예정인데, 보통 admin 페이지는 SPA가 적절해서 아예 패키지를 구분해서 렌더링하려고요

오호 넵 알겠습니다~! 그러면 admin은 제외하고 group admin만 설정해서 pr 올리도록 하겠습니다!
