### ISSUE TITLE
[Page] Workbook Problem List 페이지 구현

### ISSUE THREAD

**Issue by goo314** [skkuding/next#176]
### Describe the problem and solution

- Workbook problem list 페이지 구현

<img width="700" alt="image" src="https://user-images.githubusercontent.com/62930375/182621261-f306a440-fd2a-42a6-9bfa-1342790139d2.png">

### 사용되는 Component
- PaginationTable (#72 )

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by goo314** [comment]
제목이, 동그라미 위에 하얀 테두리가 있는 글씨인데
tailwindcss와 native css에서 글자 테두리 스타일을 지정하기 까다로워서 디자인을 바꿨습니다.
어떤가요? `176-workbook-problem-list` 브랜치에서 확인할 수 있어요

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/62930375/182653927-ec5b815f-b860-4cd3-9155-c92bbae5df08.png">

**Comment by SOLBI1028** [comment]
전 기존 디자인 + 성현님이 저번에 미팅때 보여주셨던 디자인 중 올려주신 디자인이 가장 좋기도 했고, tailwind css를 따르는게 좋을것 같아서 올려주신 디자인으로 가도 좋을 것 같습니다~!
