### ISSUE TITLE
CSS Utility Framework: Tailwind CSS

### ISSUE THREAD

**Issue by dotoleeoak** [skkuding/next#19]
### Describe the problem and solution

Tailwind CSS를 이용해 일관되고 쉽게 UI 스타일을 적용합니다.
Windi CSS와 UnoCSS 같은 대안도 있지만, 커뮤니티가 가장 큰 Tailwind를 대신해 사용할 만큼 기능이 다른 것 같진 않아 Tailwind로 정했습니다.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
UnoCSS는 설정이 많이 필요할 것 같아서 제외하고, 남은 건 Tailwind CSS와 Windi CSS이고, 중요한 건 속도와 기능 두 가지인 것 같습니다. 
속도 면에서는 현 시점에서 TailwindCSS가 밀리지는 않는 것 같습니다. TailwindCSS가 v2->v3로 올라오면서 JIT라는 컴파일러를 새로 만들었는데, 이게 WindiCSS 컴파일러의 [핵심 아이디어](https://github.com/windicss/windicss/discussions/176)를 [이용하여](https://antfu.me/posts/windicss-and-tailwind-jit) 만든 것이라고 하네요. 
기능 면에서는 TailwindCSS v3와 WindiCSS가 차이가 거의 없는 것 같아서.. 문서화가 잘 되어 있는 TailwindCSS를 사용하는 것이 더 편할 것 같습니다 👍

**Comment by jimin9038** [comment]
아직 시작 안했으면 제가 설정해봐두 될까요? 저희 프로젝트에서 자주 쓰는 Color나 Class 등 먼저 설정해두면 좋을 것 같아서요~

**Comment by dotoleeoak** [comment]
@jimin9038 넹
