### ISSUE TITLE
PaginationTable 컴포넌트 업그레이드

### ISSUE THREAD

**Issue by goo314** [skkuding/next#196]
### 1. 반응형
➡️ 화면 크기에 맞게 보이는 field의 개수를 제한합니다.
- `width => 768 px` 일 경우
    - <img width="635" alt="image" src="https://user-images.githubusercontent.com/62930375/184385291-464aa656-d114-4d69-91d8-b25c9620001c.png">

- `width < 768 px` 일 경우
    - <img width="352" alt="image" src="https://user-images.githubusercontent.com/62930375/184385368-b54bb06e-2166-4f6a-ac0f-4a4e8420f861.png">

### 2. column 크기 설정
현재 컴포넌트 코드에서는 각 column의 width값이 설정되어 있지 않아 column에서 가장 넓은 entry값에 자동적으로 맞춰집니다.
같은 내용이더라도 페이지를 이동할때 width의 통일성이 없어 보기 불편합니다(?)

➡️ column크기에 weight값을 주어 width를 통일하고자 합니다.

<img width="800" alt="image" src="https://user-images.githubusercontent.com/62930375/184387219-ddddbcb1-536a-4cae-9a90-5898ba3f8591.png">
<img width="800" alt="image" src="https://user-images.githubusercontent.com/62930375/184387260-c7b8559f-97ff-4c95-8c24-0f22c9b5b0c5.png">

### ~~3. 헤더에 정렬기능 추가~~ 
~~현재 테이블 헤더에는 글자(field 혹은 label값)만 넣을 수 있도록 설정되어 있습니다.~~

~~➡️ 헤더에 정렬기능을 추가하여 사용자가 원하는 정렬순서로 테이블을 보여주고자 합니다.~~

update 2022.8.30

<img width="519" alt="image" src="https://user-images.githubusercontent.com/62930375/184387886-01e6ce6b-7df6-41b9-bb84-ab95dbeb6854.png">

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by SOLBI1028** [comment]
지금은 테이블에서 maximum row를 결정하지 못하는것 같은데, 이부분도 추가하면 어떨까요?

**Comment by goo314** [comment]
> 지금은 테이블에서 maximum row를 결정하지 못하는것 같은데, 이부분도 추가하면 어떨까요?

오 좋아요~~ 추가해두도록 하겠습니다!
