### ISSUE TITLE
[Feature Request] Make email template

### ISSUE THREAD

**Issue by SH9480P** [skkuding/next#205]
### Describe the problem and solution

코딩 플랫폼에서 사용자에게 이메일을 보내야 할 몇 가지 상황이 존재합니다.
각 상황 별로 사용자에게 보일 페이지가 필요한데, 현재는 구현되어 있지 않습니다.
use case에 따른 맞춤 이메일 템플릿을 만들어주실 수 있으신가요?

nestjs mailer module에서 사용 가능한 템플릿 엔진은 handlebars, pug, ejs입니다.
템플릿 저장 위치는 backend/src/email/templates가 좋을 듯 싶은데(이메일 모듈이 backend/src/email에 구현됨), 더 적합한 위치가 있으면 원하시는 대로 구현해주세요.
~~Email module은 #109 에서 구현되었고, 리뷰가 끝나면 main브랜치에 머지될 예정입니다.~~
merge 되었습니다.

# Use Case (with email transfer)

### 비밀번호 재설정
사용자가 등록된 email 주소를 입력하고 이메일 인증 버튼을 클릭합니다.
입력한 email 주소로 비밀번호 재설정용 이메일을 받습니다. **이메일은 PIN 번호 6자리를 포함합니다.**
이메일에서 PIN 번호를 확인하고, 비밀번호 재설정 페이지로 돌아와서 PIN 번호를 입력합니다.
PIN 번호가 유효하다는 메세지를 받으면 새로운 비밀번호를 입력하여 변경합니다.

### 회원가입
사용자가 email 주소를 포함하여 회원가입에 필요한 각종 data를 입력하고 이메일 인증 버튼을 클릭합니다.
입력한 email 주소로 회원가입용 이메일을 받습니다. **이메일은 PIN 번호 6자리를 포함합니다.**
이메일에서 PIN 번호를 확인하고, 회원가입 페이지로 돌아와서 PIN 번호를 입력합니다.
PIN 번호가 유효하다는 메세지를 받으면 회원가입 버튼을 눌러 회원가입 절차를 마칩니다.

### 이메일 변경
로그인이 된 사용자가 프로필 페이지에서 이메일 변경 버튼을 클릭합니다.
이메일 변경을 위해 다시 로그인을 수행합니다.
이메일 변경 페이지(또는 모달)에서 변경할 이메일 주소를 입력합니다.
변경할 이메일 계정으로 이메일을 받습니다. **이메일은 PIN 번호 6자리를 포함합니다.**
이메일에서 PIN 번호를 확인하고, 이메일 변경 페이지로 돌아와서 PIN 번호를 입력합니다.
PIN 번호가 유효하다는 메세지를 받으면 변경 버튼을 눌러 이메일 변경 절차를 마칩니다.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by dotoleeoak** [comment]
제가 구현해둘게요~!
