### ISSUE TITLE
Route Path(URI)의 parameter를 camelCase로 통일

### ISSUE THREAD

**Issue by minseo999** [skkuding/next#206]
### Describe the problem and solution

현재 Route Path의 parameter를 명시할 때 camelCase와 snake_case를 혼용하고 있습니다.
이를 camelCase로 통일합니다.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by dotoleeoak** [comment]
일일이 수정하는 대신에 eslint에 rule을 추가하는 것도 가능할까요??

**Comment by minseo999** [comment]
> 일일이 수정하는 대신에 eslint에 rule을 추가하는 것도 가능할까요??

프로젝트 전체 코드에서 camelCase를 사용하도록 설정하자는 말인가요?!

**Comment by dotoleeoak** [comment]
@minseo999 convention 같은 건 수동으로 수정하는 것보단 최대한 CI가 자동으로 잡는 게 좋을 거 같아서요! typescript-eslint의 convention rule 잘 이용하면 될 것 같은데 어떨까요?

https://typescript-eslint.io/rules/naming-convention/

**Comment by minseo999** [comment]
rule 추가해서 PR 올렸습니다 논의가 필요한 부분은 PR에서 진행하면 좋을 것 같아요!
