### ISSUE TITLE
[Feature] Common(Organism) -  TextEditor

### ISSUE THREAD

**Issue by dotoleeoak** [skkuding/next#209]
### 🎨 Component Image

> **Note**
> 세부 디자인은 수정될 수 있습니다!

![image](https://user-images.githubusercontent.com/19747913/186437145-886975ec-de4f-48ec-86fe-81b0eb8729b6.png)

### ✏️ Describe component

Group admin 페이지를 비롯해서 style 적용이 필요한 글을 작성할 수 있는 WYSIWYG text editor입니다.

ProseMirror의 minimal한 wrapper인 Tiptap을 이용하여 구현합니다.
스타일링이 자유롭고 Vue 지원이 원활하다는 장점이 있습니다.

Tiptap website: https://tiptap.dev/

### ☁️ Props

WIP

### 🔎 Using Page

Group Admin 등 (추가 예정)

**Comment by jimin9038** [comment]
제가 해볼까 하는데 혹시 디자인은 상의된 바가 있나요 ??

**Comment by dotoleeoak** [comment]
Figma에 있긴 한데, 디자인은 새로 해도 상관 없을 것 같아요

![image](https://user-images.githubusercontent.com/19747913/187840873-585c79fb-7dd6-42ff-a801-9b13d5ef0ff6.png)
