### ISSUE TITLE
404 not found 페이지

### ISSUE THREAD

**Issue by dotoleeoak** [skkuding/next#221]
### Describe the problem and solution

잘못된 URL을 입력했을 때 보여줄 404 페이지를 구현합니다.
아래 사진은 제가 전에 작업해둔 페이진데, 괜찮으면 이대로 하고 다른 의견 있으면 댓글 남겨주세요~!

![image](https://user-images.githubusercontent.com/19747913/188268295-1b6f0984-f54d-4ab4-b83a-440be36e0ac9.png)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by goo314** [comment]
헐 너무 귀여워요!! 완전 좋은데요? 🤩
