### ISSUE TITLE
Add issue template for frontend page development

### ISSUE THREAD

**Issue by goo314** [skkuding/next#222]
### Describe the problem and solution

프론트엔드는 작은 단위의 component 뿐 아니라 페이지도 자주 개발합니다.
조금 늦은감이 있지만.. 페이지 구현할 때도 정형화된 이슈 템플릿이 있었으면 좋을 것 같아요!

생각해놓은 방법이 2가지가 있는데
1. 페이지 구현을 위한 새로운 issue template을 추가한다.
2. 기존 issue template을 component뿐만 아니라 page 구현에도 적용할 수 있도록 약간 수정한다.

어떤게 좋을 것 같나요?

필수적으로 들어가야할 요소는 일단 아래와 같이 생각하고 있어요.

---

# [Feature] 모듈이름(Page) - 페이지 이름
## 🎨 Screen Image
```
// 구현하고자 하는 페이지의 사진을 올려주세요.


```

## ✏️ Describe what you're going to implement
```
// 해당 페이지에 대한 설명을 적어주세요.


```

## 🏷️ Required Components
```
// 해당 페이지에 필요한 컴포넌트를 적어주세요.


```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
따로 만드는 편(1)이 좋을 것 같습니다~
페이지 단위에서는 컴포넌트와는 느낌이 다르게 필요한 API와 렌더링 순서 등을 쓰면 좋겠네요 :)

**Comment by goo314** [comment]
> 따로 만드는 편(1)이 좋을 것 같습니다~ 페이지 단위에서는 컴포넌트와는 느낌이 다르게 필요한 API와 렌더링 순서 등을 쓰면 좋겠네요 :)

좋아요~~! 반영해서 구현해보도록 하겠습니다 😁
