### ISSUE TITLE
[Feature] Problem(Molecule) -  Modal

### ISSUE THREAD

**Issue by hbsongk** [skkuding/next#236]
### 🎨 Component Image

![p_1](https://user-images.githubusercontent.com/68498323/190101313-9ab5d862-7fc8-4dc3-a0f4-5f800141b146.png)

![p_2](https://user-images.githubusercontent.com/68498323/190101335-8c533ebb-d6d0-4d7c-b9d8-e7867597a17d.png)

![p_3](https://user-images.githubusercontent.com/68498323/190101355-b1751001-65ac-4010-bf8d-08fce0608e82.png)

### ✏️ Describe component

{
My Submissions
Clarifications
All Submissions
} **Modal** 

### ☁️ Props

color: 
기존의 모달 = 흰색
**Problem 모달 = 검은색**

### 🔎 Using Page

Problem

### 🏷 Required Component

#143 Modal
#196 PaginationTable
#92 PageSubtitle

**Comment by goo314** [comment]
Problem 페이지 디자인이 변경되서 이 Issue는 닫도록 하겠습니다.
Submission은 페이지로, Clarification은 다른 component로 변경되었습니다.
