### ISSUE TITLE
[Feature] Problem - Navigator

### ISSUE THREAD

**Issue by st42597** [skkuding/next#237]
### 🎨 Component Image

<img width="1117" alt="스크린샷 2022-09-28 오전 9 06 05" src="https://user-images.githubusercontent.com/67233988/192658533-10ab9739-f17f-4fe7-841d-603f327f42b2.png">

### ✏️ Describe component

problem 탭에 hambuger, refresh, run, submit, language를 선택할 수 있는 navigator

### ☁️ Props

현재 페이지가 보고 있는 문제의 이름

### 🔎 Using Page

problem

**Comment by goo314** [comment]
컴포넌트 사진이 안보여요 😢

**Comment by st42597** [comment]
수정했습니다!
