### ISSUE TITLE
[Feature] Contest: Convert group contest into public contest 

### ISSUE THREAD

**Issue by mixxeo** [skkuding/next#62]
### 📌 Describe the feature

- `group_admin`이 group 내에서 만든 contest를 `super_manager`에게 요청하여 public contest(`group_id=1`)로 전환할 수 있도록 합니다.

### 📚 Describe related database schema

- contest
required field: group_id
- conversion_request
전환 요청을 표현하는 데이터가 필요합니다.
(1) contest 테이블에 boolean field로 추가 또는
(2) conversion_request 테이블 추가: contest_id, group_id, 승인여부 field가 필요합니다.

### 📄 Use-Case(기획)

- `group_admin`은 group 내에서 contest 생성, 문제등록까지 마친 contest에 대해 public contest로의 전환 요청을 할 수 있다.
- `super_manager`는 전환 요청을 받은 contest들의 목록과 세부사항을 확인할 수 있다.
- `super_manager`는 public contest로의 전환 요청을 승인 또는 거절할 수 있다.
- 요청이 승인되어 public contest로 전환된 contest의 수정, 삭제등의 관리는 `super_manager`만 할 수 있다.

**Comment by minseo999** [comment]
conversion_request 데이터와 관련해서,
contest 테이블에 boolean field로 추가할 경우, 직관적이지 않고 대부분의 경우(전환하지 않는 경우)에 default value로 유지되는 field가 될 것 같습니다.
그래서 새로운 테이블을 추가하는게 좋을 것 같은데 어떨까요??

**Comment by dotoleeoak** [comment]
> conversion_request 데이터와 관련해서,
> contest 테이블에 boolean field로 추가할 경우, 직관적이지 않고 대부분의 경우(전환하지 않는 경우)에 default value로 유지되는 field가 될 것 같습니다.
> 그래서 새로운 테이블을 추가하는게 좋을 것 같은데 어떨까요??

전 table 추가가 좋아보여요
메시지도 담아서 신청하게끔 하면 좋을 것 같아요
