### ISSUE TITLE
[Feature] Common(Atom) - Button

### ISSUE THREAD

**Issue by hbsongk** [skkuding/next#68]
### 🎨 Component Image

![버튼](https://user-images.githubusercontent.com/68498323/175933151-939f1106-fb22-4f30-ac6d-d2faeb2ccd69.jpg)

### ✏️ Describe component

클릭 했을 시 특정 이벤트를 발생시킵니다.

### ☁️ Props

icon : `true` / `false` (보류)

text : 버튼에 들어갈 텍스트나 아이콘 🤔

color: 버튼 색깔 (user에선 primary만 사용함)

rounded : 버튼의 테두리 모양 `true` / `false`

hover : 마우스를 갖다 댔을때 색깔 변화 `true` / `false`

### 🔎 Using Page

- main page
- problem page
- notice page
- workbook page
- contest page
- group page

**Comment by SOLBI1028** [comment]
issue 제목은 module name (component type) - Component name으로 작성해주세요!!
button의 경우, Common(Atom) - Button 이렇게 작성해주시면 될 것 같습니다 :)

**Comment by hbsongk** [comment]
> issue 제목은 module name (component type) - Component name으로 작성해주세요!! button의 경우, Common(Atom) - Button 이렇게 작성해주시면 될 것 같습니다 :)

수정했습니당~~ 빠르시네요 ㄷㄷㄷ

**Comment by goo314** [comment]
`icon` 은 있어도 되고 없어도 되는 props 같다고 생각해서 보류라고 적어놨어요~ 
만약 부모컴포넌트에서 `text`에 icon과 함께 글을 적으면 둘 다 들어가기 때문에 하나만 있어도 괜찮을 것 같다고 생각해서요!
이 부분은 구현하면서 차차 논의해보도록 하겠습니다 😉

**Comment by dotoleeoak** [comment]
지금 iconset을 iconify로 세팅해뒀는데(PR #34) button component에 slot 적용하면 icon prop 없이도 icon 쓸 수 있어요. slot 쓰면 커스텀도 더 쉬울 거에요
