### ISSUE TITLE
[Feature] Common(Molecule) -  InputItem

### ISSUE THREAD

**Issue by kee711** [skkuding/next#74]
### 🎨 Component Image

<img width="707" alt="스크린샷 2022-06-27 오후 10 03 38" src="https://user-images.githubusercontent.com/59683761/175948172-cb121d55-8031-4b54-b674-fba190e403d5.png">

### ✏️ Describe component

modal이나 page에서 사용자에게 값을 입력 받습니다.

### ☁️ Props

- label
- modelValue
- placeholder
- required : `ture` / `false`
- shadow : `true` / `false`

### 🔎 Using Page

Main-RegisterModal
Main-SignInModal
Main-PasswordRecoveryModal
Groupadmin-CreateGroup / Notice / Contest / Problem / Workbook

**Comment by goo314** [comment]
InputItem 보니까 Atom인걸요..?

**Comment by SOLBI1028** [comment]
> InputItem 보니까 Atom인걸요..? 🤔

처음엔 라벨도 있어서 Molecule로 할까 했었다가, 이번에 구현할때 사용자에게 입력을 받는다는 기능을 한다고 생각해서 Atom으로 바꾼거라 issue엔 Molecule로 되어있고, 노션이랑 구현 폴더는 Atom으로 되어있을 거에요~~
