### ISSUE TITLE
[Feature] Home(Atom)-Table

### ISSUE THREAD

**Issue by djc06048** [skkuding/next#82]
### 🎨 Component Image

<img width="553" alt="image" src="https://user-images.githubusercontent.com/62535887/178912492-7b5121c5-dace-4fd3-b385-8c365fdd99fe.png">

### ✏️ Describe component

Home에만 적용되는 table
- 헤더(tr 태그 1개) -> slot 으로 제목 변경 가능
- perPage=5 이기 때문에 보여주는 대회수는 5개(tr 태그 5개)
- 대회이름, 날짜 (td 태그 2개)

### ☁️ Props

* title
* date

### 🔎 Using Page

Home

**Comment by dotoleeoak** [comment]
#83에서 구현할게요~
