### ISSUE TITLE
Check commit message style with commitlint

### ISSUE THREAD

**Issue by dotoleeoak** [skkuding/next#96]
### Describe the problem and solution

https://commitlint.js.org/#/

[Contributing guide](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#-commit-convention-%EF%B8%8F)에서 언급한대로 commitlint로 commit style을 검사합니다.
commitlint로는 (1) 로컬에서 남기는 commit message를 git hook으로 검사하고, (2) CI(GitHub Action) 단계에서 PR title을 검사하려고 합니다. (PR title이 곧 main 브랜치에 올라가는 commit message이기 때문입니다)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by dotoleeoak** [comment]
하나 고민이 되는게 git hook에도 commitlint를 넣을지인데, 이 커밋들은 main 브랜치에는 안 들어가고 PR에서만 확인할텐데 commitlint로 스타일 강제하는건 과하게 엄격한건 아닌가 싶기도 하네요...

**Comment by cranemont** [comment]
> 하나 고민이 되는게 git hook에도 commitlint를 넣을지인데, 이 커밋들은 main 브랜치에는 안 들어가고 PR에서만 확인할텐데 commitlint로 스타일 강제하는건 과하게 엄격한건 아닌가 싶기도 하네요...

그래도 통일성 유지를 위해 그정도는 시스템적으로 강제해도 좋을 것 같아요. 로컬에도 commitlint 되어있으면 새로운 팀원이 들어왔을때 commit 스타일 익히기도 좋고, 또 PR에서 commit 확인할때도 편할 것 같습니다
