### ISSUE TITLE
Exception 도메인 도입.

### ISSUE THREAD

**Issue by Anzanda** [skkuding/next#99]
### Describe the problem and solution

Exception도메인을 도입하고자 합니다. 클라이언트에게 전달해줘야할 specific한 exception들이 많습니다.

`User`도메인을 예시로 들어보자면.
+ 이미 가입된 이메일(`signUp()`)
+ 이메일이 인증되지 않은 유저(`logIn()`)
+ 비밀번호가 일치하지 않음(`logIn()`)
등의 상황들이 있습니다.

따라서 Exception도메인을 추가하여, 클라이언트에게 올바른 데이터를 전달해줍시다. 또한 **scalable**하게 Exception도메인을 설계합니다.

### 구상

Exception들은 모두 `HttpException`을 직/간접적으로 상속받습니다. 그리고 `HttpException`을 캐치하는 custom filter(에러 핸들러)를 만들어 일정한 형식으로 클라이언트에게 전달해줍니다.

생각해본 Exception의 구성은 이렇습니다.
+ `UserException extends HttpException`
    + `DuplicatedEmailException extends UserException`
    + `UnauthorizedEmail extends UserException`
    + `MismatchedPassword extends UserException`

제 생각에 이러한 구조로 설계한다면, scalable하게 개발할 수 있을 거 같습니다.

그러면 디렉토리는 아래와 같은 구조가 될 것입니다.
+ exception
    + user
        + user.exception.ts
        + duplicated-email.exception.ts
        + . . .
    + problem
        + . . . 
    + group
        + . . . 
    + . . . 

처럼 그려질 것입니다.

### 논의해야할 점들

에러 핸들링은 상당히 중요한 영역이기 때문에, 더 고민해볼 필요가 있습니다. 의견을 전달해주시면, 적극 수용하도록 하겠습니다. 저도 더 찾아보겠습니다.

당장 생각나는 논의점들은
1. 다른 디자인 방식이 있다.
2. "statusCode", "message"를 기본적으로 보내주는데 이거 말고도 다른 필드가 필요할까? ex) "success" , . . .
3. 언급한 예시들(이미 가입된 이메일, 이메일이 인증되지 않음, 패스워드가 일치하지 않음)은 exception이 아닌 "다른 방식"으로 해결하는게 좋아보인다.

등이 있습니다. 의견 부탁드립니다.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by cranemont** [comment]
Nest에서 Controller의 역할은 request를 적절한 service에 mapping해서 response를 전달하는 거라고 생각해요. Service layer의 역할은 business logic들을 수행하는 거라고 생각하구요. 이런 관점으로 error handling을 생각해봤는데, 예외가 발생해서 client에게 관련 response를 돌려줘야 할 때 HTTP status code를 결정하는 건 controller이어야 하고, service에서는 status code에 관여하지 말아야 한다는 생각이 드네요. Service layer에서 Business logic을 수행하다가 예외가 발생했다면 service의 역할은 예외가 발생했다는 걸 해당 business logic 수행을 요청한 controller에게 알리는 것 까지고, context에 따라 해당 예외를 판단해서 적절한 status code를 가진 user-friendly한 response를 주는 건 controller의 역할이라고 생각해요. 
따라서 모든 Exception이 `HttpException`을 상속받는것보다는, `Error`를 extend하는 Business Exception class를 만들고, service에서 발생하는 business logic 관련 exception들은 해당 class를 상속받는 형태로 구현하는 게 더 좋을 것 같아요. #105 에는 일단 그렇게 구현해 두었습니다.

**Comment by cranemont** [comment]
이렇게 되면 controller에서 throw한 `HttpException`은 nest의 default exception handler가 처리해서
```json
{
  "statusCode": 404,
  "message": "data"
}
```
이런 형태로 response가 갈텐데, 정상적인 response의 경우 nest의 standard response를 사용한다면
```json
{
  "id": 1,
  "username": "haksan"
  ....
}
```
이런식으로 data만 전달이 됩니다. 그런데 이렇게 되면 FE에서 HTTP header의 status code를 보고 Request에 대해 정상적인 Response를 받았는지를 확인해야 할 것 같아요. 

그것보다는 이런 형식으로 공통의 interface를 정의하고
```typescript
export interface CustomResponse {
  success: boolean
  message: string
  data: string
}
```
`HttpException`을 처리하는 [global exception filter](https://docs.nestjs.com/exception-filters#exception-filters-1)와 일반적인 response를 처리하는 [response filter](https://docs.nestjs.com/interceptors#response-mapping)를 구현하고 동일하게 `CustomResponse`를 반환하도록 하는 건 어떨까요?

**Comment by cranemont** [comment]
좀 더 찾아보니 RESTful한 API는 
>  FE에서 HTTP header의 status code를 보고 Request에 대해 정상적인 Response를 받았는지를 확인해야 할 것 같아요.

이렇게 만드는게 정확한 방법이었네요🤔
FE에서 2xx status code인 경우에만 success로 판단하고 그에 맞는 처리를 하고, 아니라면 error에 대한 처리를 하면 될 것 같아요.

**Comment by cranemont** [comment]
근데 저렇게 하는게 맞는 방식이라면 global exception filter랑 response interceptor가 굳이 필요할까요? 🤔🤔🤔 어떻게 생각하시나요?

**Comment by Anzanda** [comment]
> Nest에서 Controller의 역할은 request를 적절한 service에 mapping해서 response를 전달하는 거라고 생각해요. Service layer의 역할은 business logic들을 수행하는 거라고 생각하구요. 이런 관점으로 error handling을 생각해봤는데, 예외가 발생해서 client에게 관련 response를 돌려줘야 할 때 HTTP status code를 결정하는 건 controller이어야 하고, service에서는 status code에 관여하지 말아야 한다는 생각이 드네요. Service layer에서 Business logic을 수행하다가 예외가 발생했다면 service의 역할은 예외가 발생했다는 걸 해당 business logic 수행을 요청한 controller에게 알리는 것 까지고, context에 따라 해당 예외를 판단해서 적절한 status code를 가진 user-friendly한 response를 주는 건 controller의 역할이라고 생각해요. 
> 
> 따라서 모든 Exception이 `HttpException`을 상속받는것보다는, `Error`를 extend하는 Business Exception class를 만들고, service에서 발생하는 business logic 관련 exception들은 해당 class를 상속받는 형태로 구현하는 게 더 좋을 것 같아요. #105 에는 일단 그렇게 구현해 두었습니다.

1. Service계층에서 statusCode에 관여하면 안 된다.
2. 예외가 발생했다는 것을 Controller에 알려야 한다.
3. Error throw하여 컨트롤러에서 받고 이를 response로 보내자.

먼저 Spring들먹이는 점 죄송합니다. Nest.js가 Spring과 디자인패턴적으로 평행하게 흐르는 점이 많다고 생각하여 언급하게 되네요.

Spring의 `@RestControllerAdvice`를 아시나요? 저는 이게 Nest.js의 Filter와 같다고 생각했습니다.

``` java

@RestControllerAdvice
public class GlobalExceptionHandler {

    @ExceptionHandler(NoSuchElementFoundException.class)
    protected ResponseEntity<?> handleIllegalArgumentException(NoSuchElementFoundException e) {
        final ErrorResponse errorResponse = ErrorResponse.builder()
                .code("Item Not Found")
                .message(e.getMessage()).build();

        return ResponseEntity.status(HttpStatus.NOT_FOUND).body(errorResponse);
    }
}

// 출처: https://mangkyu.tistory.com/205 [MangKyu's Diary:티스토리]
```

이렇게들 씁니다. 정확히는 뭔지 모를 수 있겠지만, 어느정도의 틀은 잡혔다고 생각하고 넘어갈게요.

``` typescript

import { ExceptionFilter, Catch, ArgumentsHost, HttpException } from '@nestjs/common';
import { Request, Response } from 'express';

@Catch(HttpException)
export class HttpExceptionFilter implements ExceptionFilter {
  catch(exception: HttpException, host: ArgumentsHost) {
    const ctx = host.switchToHttp();
    const response = ctx.getResponse<Response>();
    const request = ctx.getRequest<Request>();
    const status = exception.getStatus();

    response
      .status(status)
      .json({
        statusCode: status,
        timestamp: new Date().toISOString(),
        path: request.url,
      });
  }
}

// 출처: Nest.js docs
```

어떤가요 비슷하지 않나요? Nest.js의 자료가 그렇게 방대하지 않다보니 Spring을 들먹이는점 다시 한 번 양해부탁드립니다.

그래서 하고 싶은 말은. Nest.js의 Filter가 Controller의 역할을 한다는 것입니다. 즉, Service에서 Exception을 throw하면 Filter라는 Controller로 가는 거죠. 그러므로 Service계층 본연의 의미는 안 잃는다는 결론입니다.

`HttpException`을 상속받자는 의도도 얘기해볼게요. 따로 CustomErrorHandler(CustomFilter)를 만들어도 되겠지만, 일단은 그럴 필요가 굳이 없어보이고, default error handler(default filter)만으로도 잘 돌아가니까요. 확장할꺼면 default를 거의 override한 급의 `success`정도를 추가할건데 문제 없을거라 생각했어요.
